
version: 2

models:
    - name: sql_1
      description: "A "
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: sql_2
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: final
      description: "A starter dbt"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
